//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/plugins/PPluginBackgroundDestroyerParent.h"
#include "mozilla/ProfilerLabels.h"

#include "mozilla/plugins/PPluginInstanceParent.h"

#include "ipc/IPCMessageUtils.h"
#include "nsIFile.h"
#include "mozilla/ipc/Endpoint.h"
#include "mozilla/ipc/ProtocolMessageUtils.h"
#include "mozilla/ipc/ProtocolUtils.h"
#include "mozilla/ipc/ShmemMessageUtils.h"
#include "mozilla/ipc/TaintingIPCUtils.h"

namespace mozilla {
namespace plugins {


auto PPluginBackgroundDestroyerParent::Recv__delete__() -> mozilla::ipc::IPCResult
{
    return IPC_OK();
}

MOZ_IMPLICIT PPluginBackgroundDestroyerParent::PPluginBackgroundDestroyerParent() :
    mozilla::ipc::IProtocol(PPluginBackgroundDestroyerMsgStart, mozilla::ipc::ParentSide)
{
    MOZ_COUNT_CTOR(PPluginBackgroundDestroyerParent);
}

PPluginBackgroundDestroyerParent::~PPluginBackgroundDestroyerParent()
{
    MOZ_COUNT_DTOR(PPluginBackgroundDestroyerParent);
}

auto PPluginBackgroundDestroyerParent::Manager() const -> PPluginInstanceParent*
{
    return static_cast<PPluginInstanceParent*>(IProtocol::Manager());
}

auto PPluginBackgroundDestroyerParent::AllManagedActors(nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy>>& arr__) const -> void
{
    uint32_t total = 0;
    arr__.SetCapacity(total);

}

auto PPluginBackgroundDestroyerParent::RemoveManagee(
        int32_t aProtocolId,
        IProtocol* aListener) -> void
{
    FatalError("unreached");
    return;
}

auto PPluginBackgroundDestroyerParent::DeallocManagee(
        int32_t aProtocolId,
        IProtocol* aListener) -> void
{
    FatalError("unreached");
    return;
}

auto PPluginBackgroundDestroyerParent::OnMessageReceived(const Message& msg__) -> PPluginBackgroundDestroyerParent::Result
{
    switch (msg__.type()) {
    case PPluginBackgroundDestroyer::Msg___delete____ID:
        {
            if (mozilla::ipc::LoggingEnabledFor("PPluginBackgroundDestroyerParent")) {
                mozilla::ipc::LogMessageForProtocol(
                    "PPluginBackgroundDestroyerParent",
                    OtherPid(),
                    "Received ",
                    (&(msg__))->type(),
                    mozilla::ipc::MessageDirection::eReceiving);
            }
            AUTO_PROFILER_LABEL("PPluginBackgroundDestroyer::Msg___delete__", OTHER);

            PickleIterator iter__{msg__};
            PPluginBackgroundDestroyerParent* actor{};

            if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(actor)))))) {
                FatalError("Error deserializing 'PPluginBackgroundDestroyer'");
                return MsgValueError;
            }
            if ((!((*((&(actor))))))) {
                FatalError("Error deserializing 'PPluginBackgroundDestroyer'");
                return MsgValueError;
            }
            // Sentinel = 'actor'
            if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 102892058)))) {
                mozilla::ipc::SentinelReadError("Error deserializing 'PPluginBackgroundDestroyer'");
                return MsgValueError;
            }
            msg__.EndRead(iter__, msg__.type());
            if ((!((this)->Recv__delete__()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler returned error code!");
                // Error handled in mozilla::ipc::IPCResult
                return MsgProcessingError;
            }


            IProtocol* mgr = actor->Manager();
            actor->DestroySubtree(Deletion);
            actor->ClearSubtree();
            mgr->RemoveManagee(PPluginBackgroundDestroyerMsgStart, actor);

            return MsgProcessed;
        }
    default:
        return MsgNotKnown;
    }
}

auto PPluginBackgroundDestroyerParent::OnMessageReceived(
        const Message& msg__,
        Message*& reply__) -> PPluginBackgroundDestroyerParent::Result
{
    return MsgNotKnown;
}

auto PPluginBackgroundDestroyerParent::OnCallReceived(
        const Message& msg__,
        Message*& reply__) -> PPluginBackgroundDestroyerParent::Result
{
    return MsgNotKnown;
}

auto PPluginBackgroundDestroyerParent::ClearSubtree() -> void
{
}



} // namespace plugins
} // namespace mozilla
namespace mozilla {
namespace ipc {
auto IPDLParamTraits<mozilla::plugins::PPluginBackgroundDestroyerParent*>::Write(
        IPC::Message* aMsg,
        mozilla::ipc::IProtocol* aActor,
        const paramType& aVar) -> void
{
    int32_t id;
    if (!aVar) {
        id = 0;  // kNullActorId
    } else {
        id = aVar->Id();
        if (id == 1) {  // kFreedActorId
            aVar->FatalError("Actor has been |delete|d");
        }
        MOZ_RELEASE_ASSERT(
            aActor->GetIPCChannel() == aVar->GetIPCChannel(),
            "Actor must be from the same channel as the"
            " actor it's being sent over");
        MOZ_RELEASE_ASSERT(
            aVar->CanSend(),
            "Actor must still be open when sending");
    }

    WriteIPDLParam(aMsg, aActor, id);
}

auto IPDLParamTraits<mozilla::plugins::PPluginBackgroundDestroyerParent*>::Read(
        const IPC::Message* aMsg,
        PickleIterator* aIter,
        mozilla::ipc::IProtocol* aActor,
        paramType* aVar) -> bool
{
    mozilla::Maybe<mozilla::ipc::IProtocol*> actor =
        aActor->ReadActor(aMsg, aIter, true, "PPluginBackgroundDestroyer", PPluginBackgroundDestroyerMsgStart);
    if (actor.isNothing()) {
        return false;
    }

    *aVar = static_cast<mozilla::plugins::PPluginBackgroundDestroyerParent*>(actor.value());
    return true;
}

} // namespace ipc
} // namespace mozilla
