//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/dom/PRemoteWorkerChild.h"
#include "mozilla/ProfilerLabels.h"
#include "mozilla/dom/RemoteWorkerChild.h"

#include "mozilla/ipc/PBackgroundChild.h"
#include "mozilla/dom/PFetchEventOpProxyChild.h"

#include "ipc/IPCMessageUtils.h"
#include "nsIFile.h"
#include "mozilla/ipc/Endpoint.h"
#include "mozilla/ipc/ProtocolMessageUtils.h"
#include "mozilla/ipc/ProtocolUtils.h"
#include "mozilla/ipc/ShmemMessageUtils.h"
#include "mozilla/ipc/TaintingIPCUtils.h"

namespace mozilla {
namespace dom {


auto PRemoteWorkerChild::RecvPFetchEventOpProxyConstructor(
        PFetchEventOpProxyChild* actor,
        const ServiceWorkerFetchEventOpArgs& aArgs) -> mozilla::ipc::IPCResult
{
    return IPC_OK();
}

auto PRemoteWorkerChild::Recv__delete__() -> mozilla::ipc::IPCResult
{
    return IPC_OK();
}

MOZ_IMPLICIT PRemoteWorkerChild::PRemoteWorkerChild() :
    mozilla::ipc::IProtocol(PRemoteWorkerMsgStart, mozilla::ipc::ChildSide)
{
    MOZ_COUNT_CTOR(PRemoteWorkerChild);
}

PRemoteWorkerChild::~PRemoteWorkerChild()
{
    MOZ_COUNT_DTOR(PRemoteWorkerChild);
}

auto PRemoteWorkerChild::Manager() const -> PBackgroundChild*
{
    return static_cast<PBackgroundChild*>(IProtocol::Manager());
}

auto PRemoteWorkerChild::ManagedPFetchEventOpProxyChild(nsTArray<PFetchEventOpProxyChild*>& aArr) const -> void
{
    mManagedPFetchEventOpProxyChild.ToArray(aArr);
}

auto PRemoteWorkerChild::ManagedPFetchEventOpProxyChild() const -> const ManagedContainer<PFetchEventOpProxyChild>&
{
    return mManagedPFetchEventOpProxyChild;
}

auto PRemoteWorkerChild::AllManagedActors(nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy>>& arr__) const -> void
{
    uint32_t total = 0;
    total += mManagedPFetchEventOpProxyChild.Count();
    arr__.SetCapacity(total);

    for (auto it = mManagedPFetchEventOpProxyChild.ConstIter(); !it.Done(); it.Next()) {
        arr__.AppendElement(it.Get()->GetKey()->GetLifecycleProxy());
    }

}

auto PRemoteWorkerChild::OpenPFetchEventOpProxyEndpoint(PFetchEventOpProxyChild* aActor) -> ManagedEndpoint<PFetchEventOpProxyParent>
{
    if (!aActor) {
        NS_WARNING("Cannot bind null PFetchEventOpProxyChild actor");
        return ManagedEndpoint<PFetchEventOpProxyParent>();
    }

    aActor->SetManagerAndRegister(this);
    mManagedPFetchEventOpProxyChild.PutEntry(aActor);

    return ManagedEndpoint<PFetchEventOpProxyParent>(mozilla::ipc::PrivateIPDLInterface(), aActor->Id());
}

auto PRemoteWorkerChild::BindPFetchEventOpProxyEndpoint(
        ManagedEndpoint<PFetchEventOpProxyChild> aEndpoint,
        PFetchEventOpProxyChild* aActor) -> bool
{
    MOZ_RELEASE_ASSERT(aEndpoint.ActorId(), "Invalid Endpoint!");
    if (!aActor) {
        NS_WARNING("Cannot bind null PFetchEventOpProxyChild actor");
        return false;
    }

    aActor->SetManagerAndRegister(this, *aEndpoint.ActorId());
    mManagedPFetchEventOpProxyChild.PutEntry(aActor);

    return true;
}

auto PRemoteWorkerChild::SendCreated(const bool& aStatus) -> bool
{
    IPC::Message* msg__ = PRemoteWorker::Msg_Created(Id());

    WriteIPDLParam(msg__, this, aStatus);
    // Sentinel = 'aStatus'
    (msg__)->WriteSentinel(186712806);




    if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PRemoteWorkerChild",
            OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PRemoteWorker::Msg_Created", OTHER);

    bool sendok__ = ChannelSend(msg__);
    return sendok__;
}

auto PRemoteWorkerChild::SendError(const ErrorValue& aValue) -> bool
{
    IPC::Message* msg__ = PRemoteWorker::Msg_Error(Id());

    WriteIPDLParam(msg__, this, aValue);
    // Sentinel = 'aValue'
    (msg__)->WriteSentinel(135332447);




    if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PRemoteWorkerChild",
            OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PRemoteWorker::Msg_Error", OTHER);

    bool sendok__ = ChannelSend(msg__);
    return sendok__;
}

auto PRemoteWorkerChild::SendClose() -> bool
{
    IPC::Message* msg__ = PRemoteWorker::Msg_Close(Id());





    if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PRemoteWorkerChild",
            OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PRemoteWorker::Msg_Close", OTHER);

    bool sendok__ = ChannelSend(msg__);
    return sendok__;
}

auto PRemoteWorkerChild::SendSetServiceWorkerSkipWaitingFlag(
        mozilla::ipc::ResolveCallback<bool>&& aResolve,
        mozilla::ipc::RejectCallback&& aReject) -> void
{
    IPC::Message* msg__ = PRemoteWorker::Msg_SetServiceWorkerSkipWaitingFlag(Id());





    if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PRemoteWorkerChild",
            OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PRemoteWorker::Msg_SetServiceWorkerSkipWaitingFlag", OTHER);

    ChannelSend(msg__, std::move(aResolve), std::move(aReject));
    return;
}

auto PRemoteWorkerChild::SendSetServiceWorkerSkipWaitingFlag() -> RefPtr<SetServiceWorkerSkipWaitingFlagPromise>
{
    RefPtr<MozPromise<bool, ResponseRejectReason, true>::Private> promise__ = new MozPromise<bool, ResponseRejectReason, true>::Private(__func__);
    promise__->UseDirectTaskDispatch(__func__);
    SendSetServiceWorkerSkipWaitingFlag([promise__](bool&& aValue) {
        promise__->Resolve(std::move(aValue), __func__);
    }, [promise__](ResponseRejectReason&& aReason) {
        promise__->Reject(std::move(aReason), __func__);
    });
    return promise__;
}

auto PRemoteWorkerChild::RemoveManagee(
        int32_t aProtocolId,
        IProtocol* aListener) -> void
{
    switch (aProtocolId) {
    case PFetchEventOpProxyMsgStart:
{
            PFetchEventOpProxyChild* actor = static_cast<PFetchEventOpProxyChild*>(aListener);
            auto& container = mManagedPFetchEventOpProxyChild;

            // Use a temporary variable here so all the assertion expressions
            // in the MOZ_RELEASE_ASSERT call below are textually identical;
            // the linker can then merge the strings from the assertion macro(s).
            MOZ_RELEASE_ASSERT(container.Contains(actor),
                "actor not managed by this!");
            container.RemoveEntry(actor);

            auto* proxy = actor->GetLifecycleProxy();
            NS_IF_RELEASE(proxy);
            return;
        }    default:
FatalError("unreached");
        return;    }
}

auto PRemoteWorkerChild::DeallocManagee(
        int32_t aProtocolId,
        IProtocol* aListener) -> void
{
    switch (aProtocolId) {
    case PFetchEventOpProxyMsgStart:
        static_cast<RemoteWorkerChild*>(this)->DeallocPFetchEventOpProxyChild(static_cast<PFetchEventOpProxyChild*>(aListener));
        return;
    default:
        FatalError("unreached");
        return;
    }
}

auto PRemoteWorkerChild::OnMessageReceived(const Message& msg__) -> PRemoteWorkerChild::Result
{
    switch (msg__.type()) {
    case PRemoteWorker::Reply_SetServiceWorkerSkipWaitingFlag__ID:
        {
            if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
                mozilla::ipc::LogMessageForProtocol(
                    "PRemoteWorkerChild",
                    OtherPid(),
                    "Received ",
                    (&(msg__))->type(),
                    mozilla::ipc::MessageDirection::eReceiving);
            }
            AUTO_PROFILER_LABEL("PRemoteWorker::Msg_SetServiceWorkerSkipWaitingFlag", OTHER);

            PickleIterator iter__{msg__};
            bool resolve__ = false;
            if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(resolve__)))))) {
                FatalError("Error deserializing 'resolve__'");
                return MsgValueError;
            }
            // Sentinel = 'resolve__'
            if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 322044863)))) {
                mozilla::ipc::SentinelReadError("Error deserializing 'resolve__'");
                return MsgValueError;
            }


            UniquePtr<MessageChannel::UntypedCallbackHolder> untypedCallback =
                GetIPCChannel()->PopCallback(msg__);

            typedef MessageChannel::CallbackHolder<bool> CallbackHolder;
            auto* callback = static_cast<CallbackHolder*>(untypedCallback.get());
            if (!callback) {
                FatalError("Error unknown callback");
                return MsgProcessingError;
            }

            if (resolve__) {
                bool aOk{};

                if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(aOk)))))) {
                    FatalError("Error deserializing 'bool'");
                    return MsgValueError;
                }
                // Sentinel = 'aOk'
                if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 36634908)))) {
                    mozilla::ipc::SentinelReadError("Error deserializing 'bool'");
                    return MsgValueError;
                }
                msg__.EndRead(iter__, msg__.type());

                callback->Resolve(std::move(aOk));
            } else {
                ResponseRejectReason reason__{};
                if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(reason__)))))) {
                    FatalError("Error deserializing 'reason__'");
                    return MsgValueError;
                }
                // Sentinel = 'reason__'
                if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 251855687)))) {
                    mozilla::ipc::SentinelReadError("Error deserializing 'reason__'");
                    return MsgValueError;
                }
                msg__.EndRead(iter__, msg__.type());

                callback->Reject(std::move(reason__));
            }
            return MsgProcessed;
        }
    case PRemoteWorker::Msg_PFetchEventOpProxyConstructor__ID:
        {
            if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
                mozilla::ipc::LogMessageForProtocol(
                    "PRemoteWorkerChild",
                    OtherPid(),
                    "Received ",
                    (&(msg__))->type(),
                    mozilla::ipc::MessageDirection::eReceiving);
            }
            AUTO_PROFILER_LABEL("PRemoteWorker::Msg_PFetchEventOpProxyConstructor", OTHER);

            PickleIterator iter__{msg__};
            ActorHandle handle__{};
            ServiceWorkerFetchEventOpArgs aArgs{};

            if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(handle__)))))) {
                FatalError("Error deserializing 'ActorHandle'");
                return MsgValueError;
            }
            // Sentinel = 'actor'
            if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 102892058)))) {
                mozilla::ipc::SentinelReadError("Error deserializing 'ActorHandle'");
                return MsgValueError;
            }
            if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(aArgs)))))) {
                FatalError("Error deserializing 'ServiceWorkerFetchEventOpArgs'");
                return MsgValueError;
            }
            // Sentinel = 'aArgs'
            if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 92602863)))) {
                mozilla::ipc::SentinelReadError("Error deserializing 'ServiceWorkerFetchEventOpArgs'");
                return MsgValueError;
            }
            msg__.EndRead(iter__, msg__.type());
            PFetchEventOpProxyChild* actor = (static_cast<RemoteWorkerChild*>(this))->AllocPFetchEventOpProxyChild(aArgs);
            if (!actor) {
                NS_WARNING("Cannot bind null PFetchEventOpProxyChild actor");
                return MsgValueError;
            }

            actor->SetManagerAndRegister(this, (handle__).mId);
            mManagedPFetchEventOpProxyChild.PutEntry(actor);

            if ((!((static_cast<RemoteWorkerChild*>(this))->RecvPFetchEventOpProxyConstructor(std::move(actor), std::move(aArgs))))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler returned error code!");
                // Error handled in mozilla::ipc::IPCResult
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    case PRemoteWorker::Msg___delete____ID:
        {
            if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
                mozilla::ipc::LogMessageForProtocol(
                    "PRemoteWorkerChild",
                    OtherPid(),
                    "Received ",
                    (&(msg__))->type(),
                    mozilla::ipc::MessageDirection::eReceiving);
            }
            AUTO_PROFILER_LABEL("PRemoteWorker::Msg___delete__", OTHER);

            PickleIterator iter__{msg__};
            PRemoteWorkerChild* actor{};

            if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(actor)))))) {
                FatalError("Error deserializing 'PRemoteWorker'");
                return MsgValueError;
            }
            if ((!((*((&(actor))))))) {
                FatalError("Error deserializing 'PRemoteWorker'");
                return MsgValueError;
            }
            // Sentinel = 'actor'
            if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 102892058)))) {
                mozilla::ipc::SentinelReadError("Error deserializing 'PRemoteWorker'");
                return MsgValueError;
            }
            msg__.EndRead(iter__, msg__.type());
            if ((!((static_cast<RemoteWorkerChild*>(this))->Recv__delete__()))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler returned error code!");
                // Error handled in mozilla::ipc::IPCResult
                return MsgProcessingError;
            }


            IProtocol* mgr = actor->Manager();
            actor->DestroySubtree(Deletion);
            actor->ClearSubtree();
            mgr->RemoveManagee(PRemoteWorkerMsgStart, actor);

            return MsgProcessed;
        }
    case PRemoteWorker::Msg_ExecOp__ID:
        {
            if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
                mozilla::ipc::LogMessageForProtocol(
                    "PRemoteWorkerChild",
                    OtherPid(),
                    "Received ",
                    (&(msg__))->type(),
                    mozilla::ipc::MessageDirection::eReceiving);
            }
            AUTO_PROFILER_LABEL("PRemoteWorker::Msg_ExecOp", OTHER);

            PickleIterator iter__{msg__};
            RemoteWorkerOp op{};

            if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(op)))))) {
                FatalError("Error deserializing 'RemoteWorkerOp'");
                return MsgValueError;
            }
            // Sentinel = 'op'
            if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 22020320)))) {
                mozilla::ipc::SentinelReadError("Error deserializing 'RemoteWorkerOp'");
                return MsgValueError;
            }
            msg__.EndRead(iter__, msg__.type());
            if ((!((static_cast<RemoteWorkerChild*>(this))->RecvExecOp(std::move(op))))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler returned error code!");
                // Error handled in mozilla::ipc::IPCResult
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    case PRemoteWorker::Msg_ExecServiceWorkerOp__ID:
        {
            if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
                mozilla::ipc::LogMessageForProtocol(
                    "PRemoteWorkerChild",
                    OtherPid(),
                    "Received ",
                    (&(msg__))->type(),
                    mozilla::ipc::MessageDirection::eReceiving);
            }
            AUTO_PROFILER_LABEL("PRemoteWorker::Msg_ExecServiceWorkerOp", OTHER);

            PickleIterator iter__{msg__};
            ServiceWorkerOpArgs aArgs{};

            if ((!(ReadIPDLParam((&(msg__)), (&(iter__)), this, (&(aArgs)))))) {
                FatalError("Error deserializing 'ServiceWorkerOpArgs'");
                return MsgValueError;
            }
            // Sentinel = 'aArgs'
            if ((!(((&(msg__)))->ReadSentinel((&(iter__)), 92602863)))) {
                mozilla::ipc::SentinelReadError("Error deserializing 'ServiceWorkerOpArgs'");
                return MsgValueError;
            }
            msg__.EndRead(iter__, msg__.type());
            int32_t id__ = Id();
            int32_t seqno__ = msg__.seqno();
            RefPtr<mozilla::ipc::ActorLifecycleProxy> proxy__ =
                GetLifecycleProxy();

            ExecServiceWorkerOpResolver resolver = [proxy__, seqno__, id__](const ServiceWorkerOpResult& aParam) {
                if (!proxy__->Get()) {
                    NS_WARNING("Not resolving response because actor is dead.");
                    return;
                }
                PRemoteWorkerChild* self__ = static_cast<PRemoteWorkerChild*>(proxy__->Get());

                IPC::Message* reply__ = PRemoteWorker::Reply_ExecServiceWorkerOp(id__);
                reply__->set_seqno(seqno__);

                bool resolve__ = true;
                WriteIPDLParam(reply__, self__, resolve__);
                // Sentinel = 'resolve__'
                (reply__)->WriteSentinel(322044863);
                WriteIPDLParam(reply__, self__, aParam);
                // Sentinel = 'aResult'
                (reply__)->WriteSentinel(185205473);

                if (mozilla::ipc::LoggingEnabledFor("PRemoteWorkerChild")) {
                    mozilla::ipc::LogMessageForProtocol(
                        "PRemoteWorkerChild",
                        (self__)->OtherPid(),
                        "Sending reply ",
                        reply__->type(),
                        mozilla::ipc::MessageDirection::eSending);
                }

                bool sendok__ = self__->ChannelSend(reply__);
                if (!sendok__) {
                    NS_WARNING("Error sending reply");
                }
            };
            if ((!((static_cast<RemoteWorkerChild*>(this))->RecvExecServiceWorkerOp(std::move(aArgs), std::move(resolver))))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler returned error code!");
                // Error handled in mozilla::ipc::IPCResult
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    default:
        return MsgNotKnown;
    }
}

auto PRemoteWorkerChild::OnMessageReceived(
        const Message& msg__,
        Message*& reply__) -> PRemoteWorkerChild::Result
{
    return MsgNotKnown;
}

auto PRemoteWorkerChild::OnCallReceived(
        const Message& msg__,
        Message*& reply__) -> PRemoteWorkerChild::Result
{
    MOZ_ASSERT_UNREACHABLE("message protocol not supported");
    return MsgNotKnown;
}

auto PRemoteWorkerChild::ClearSubtree() -> void
{
    for (auto it = mManagedPFetchEventOpProxyChild.Iter(); !it.Done(); it.Next()) {
        it.Get()->GetKey()->ClearSubtree();
    }
    for (auto it = mManagedPFetchEventOpProxyChild.Iter(); !it.Done(); it.Next()) {
        // Recursively releasing mManagedPFetchEventOpProxyChild kids.
        auto* proxy = it.Get()->GetKey()->GetLifecycleProxy();
        NS_IF_RELEASE(proxy);
    }
    mManagedPFetchEventOpProxyChild.Clear();

}



} // namespace dom
} // namespace mozilla
namespace mozilla {
namespace ipc {
auto IPDLParamTraits<mozilla::dom::PRemoteWorkerChild*>::Write(
        IPC::Message* aMsg,
        mozilla::ipc::IProtocol* aActor,
        const paramType& aVar) -> void
{
    int32_t id;
    if (!aVar) {
        id = 0;  // kNullActorId
    } else {
        id = aVar->Id();
        if (id == 1) {  // kFreedActorId
            aVar->FatalError("Actor has been |delete|d");
        }
        MOZ_RELEASE_ASSERT(
            aActor->GetIPCChannel() == aVar->GetIPCChannel(),
            "Actor must be from the same channel as the"
            " actor it's being sent over");
        MOZ_RELEASE_ASSERT(
            aVar->CanSend(),
            "Actor must still be open when sending");
    }

    WriteIPDLParam(aMsg, aActor, id);
}

auto IPDLParamTraits<mozilla::dom::PRemoteWorkerChild*>::Read(
        const IPC::Message* aMsg,
        PickleIterator* aIter,
        mozilla::ipc::IProtocol* aActor,
        paramType* aVar) -> bool
{
    mozilla::Maybe<mozilla::ipc::IProtocol*> actor =
        aActor->ReadActor(aMsg, aIter, true, "PRemoteWorker", PRemoteWorkerMsgStart);
    if (actor.isNothing()) {
        return false;
    }

    *aVar = static_cast<mozilla::dom::PRemoteWorkerChild*>(actor.value());
    return true;
}

} // namespace ipc
} // namespace mozilla
