//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/PWebBrowserPersistResourcesChild.h"
#include "mozilla/ProfilerLabels.h"

#include "mozilla/PWebBrowserPersistDocumentChild.h"

#include "ipc/IPCMessageUtils.h"
#include "nsIFile.h"
#include "mozilla/ipc/Endpoint.h"
#include "mozilla/ipc/ProtocolMessageUtils.h"
#include "mozilla/ipc/ProtocolUtils.h"
#include "mozilla/ipc/ShmemMessageUtils.h"
#include "mozilla/ipc/TaintingIPCUtils.h"

namespace mozilla {


MOZ_IMPLICIT PWebBrowserPersistResourcesChild::PWebBrowserPersistResourcesChild() :
    mozilla::ipc::IProtocol(PWebBrowserPersistResourcesMsgStart, mozilla::ipc::ChildSide)
{
    MOZ_COUNT_CTOR(PWebBrowserPersistResourcesChild);
}

PWebBrowserPersistResourcesChild::~PWebBrowserPersistResourcesChild()
{
    MOZ_COUNT_DTOR(PWebBrowserPersistResourcesChild);
}

auto PWebBrowserPersistResourcesChild::Manager() const -> PWebBrowserPersistDocumentChild*
{
    return static_cast<PWebBrowserPersistDocumentChild*>(IProtocol::Manager());
}

auto PWebBrowserPersistResourcesChild::AllManagedActors(nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy>>& arr__) const -> void
{
    uint32_t total = 0;
    arr__.SetCapacity(total);

}

auto PWebBrowserPersistResourcesChild::SendVisitResource(
        const nsCString& aURI,
        const nsContentPolicyType& aContentPolicyType) -> bool
{
    IPC::Message* msg__ = PWebBrowserPersistResources::Msg_VisitResource(Id());

    WriteIPDLParam(msg__, this, aURI);
    // Sentinel = 'aURI'
    (msg__)->WriteSentinel(57934162);
    WriteIPDLParam(msg__, this, aContentPolicyType);
    // Sentinel = 'aContentPolicyType'
    (msg__)->WriteSentinel(1145767759);




    if (mozilla::ipc::LoggingEnabledFor("PWebBrowserPersistResourcesChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PWebBrowserPersistResourcesChild",
            OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PWebBrowserPersistResources::Msg_VisitResource", OTHER);

    bool sendok__ = ChannelSend(msg__);
    return sendok__;
}

auto PWebBrowserPersistResourcesChild::SendVisitDocument(PWebBrowserPersistDocumentChild* aSubDocument) -> bool
{
    IPC::Message* msg__ = PWebBrowserPersistResources::Msg_VisitDocument(Id());

    MOZ_RELEASE_ASSERT(aSubDocument, "NULL actor value passed to non-nullable param");
    WriteIPDLParam(msg__, this, aSubDocument);
    // Sentinel = 'aSubDocument'
    (msg__)->WriteSentinel(505677003);




    if (mozilla::ipc::LoggingEnabledFor("PWebBrowserPersistResourcesChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PWebBrowserPersistResourcesChild",
            OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PWebBrowserPersistResources::Msg_VisitDocument", OTHER);

    bool sendok__ = ChannelSend(msg__);
    return sendok__;
}

auto PWebBrowserPersistResourcesChild::SendVisitBrowsingContext(const MaybeDiscardedBrowsingContext& aContext) -> bool
{
    IPC::Message* msg__ = PWebBrowserPersistResources::Msg_VisitBrowsingContext(Id());

    WriteIPDLParam(msg__, this, aContext);
    // Sentinel = 'aContext'
    (msg__)->WriteSentinel(235406151);




    if (mozilla::ipc::LoggingEnabledFor("PWebBrowserPersistResourcesChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PWebBrowserPersistResourcesChild",
            OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PWebBrowserPersistResources::Msg_VisitBrowsingContext", OTHER);

    bool sendok__ = ChannelSend(msg__);
    return sendok__;
}

auto PWebBrowserPersistResourcesChild::Send__delete__(
        PWebBrowserPersistResourcesChild* actor,
        const nsresult& aStatus) -> bool
{
    if (!actor || !actor->CanSend()) {
        NS_WARNING("Attempt to __delete__ missing or closed actor");
        return false;
    }
    IPC::Message* msg__ = PWebBrowserPersistResources::Msg___delete__((actor)->Id());

    MOZ_RELEASE_ASSERT(actor, "NULL actor value passed to non-nullable param");
    WriteIPDLParam(msg__, actor, actor);
    // Sentinel = 'actor'
    (msg__)->WriteSentinel(102892058);
    WriteIPDLParam(msg__, actor, aStatus);
    // Sentinel = 'aStatus'
    (msg__)->WriteSentinel(186712806);



    if (mozilla::ipc::LoggingEnabledFor("PWebBrowserPersistResourcesChild")) {
        mozilla::ipc::LogMessageForProtocol(
            "PWebBrowserPersistResourcesChild",
            (actor)->OtherPid(),
            "Sending ",
            msg__->type(),
            mozilla::ipc::MessageDirection::eSending);
    }
    AUTO_PROFILER_LABEL("PWebBrowserPersistResources::Msg___delete__", OTHER);

    bool sendok__ = (actor)->ChannelSend(msg__);

    IProtocol* mgr = actor->Manager();
    actor->DestroySubtree(Deletion);
    actor->ClearSubtree();
    mgr->RemoveManagee(PWebBrowserPersistResourcesMsgStart, actor);
    return sendok__;
}

auto PWebBrowserPersistResourcesChild::RemoveManagee(
        int32_t aProtocolId,
        IProtocol* aListener) -> void
{
    FatalError("unreached");
    return;
}

auto PWebBrowserPersistResourcesChild::DeallocManagee(
        int32_t aProtocolId,
        IProtocol* aListener) -> void
{
    FatalError("unreached");
    return;
}

auto PWebBrowserPersistResourcesChild::OnMessageReceived(const Message& msg__) -> PWebBrowserPersistResourcesChild::Result
{
    switch (msg__.type()) {
    case PWebBrowserPersistResources::Reply___delete____ID:
        {
            return MsgProcessed;
        }
    default:
        return MsgNotKnown;
    }
}

auto PWebBrowserPersistResourcesChild::OnMessageReceived(
        const Message& msg__,
        Message*& reply__) -> PWebBrowserPersistResourcesChild::Result
{
    return MsgNotKnown;
}

auto PWebBrowserPersistResourcesChild::OnCallReceived(
        const Message& msg__,
        Message*& reply__) -> PWebBrowserPersistResourcesChild::Result
{
    MOZ_ASSERT_UNREACHABLE("message protocol not supported");
    return MsgNotKnown;
}

auto PWebBrowserPersistResourcesChild::ClearSubtree() -> void
{
}



} // namespace mozilla
namespace mozilla {
namespace ipc {
auto IPDLParamTraits<mozilla::PWebBrowserPersistResourcesChild*>::Write(
        IPC::Message* aMsg,
        mozilla::ipc::IProtocol* aActor,
        const paramType& aVar) -> void
{
    int32_t id;
    if (!aVar) {
        id = 0;  // kNullActorId
    } else {
        id = aVar->Id();
        if (id == 1) {  // kFreedActorId
            aVar->FatalError("Actor has been |delete|d");
        }
        MOZ_RELEASE_ASSERT(
            aActor->GetIPCChannel() == aVar->GetIPCChannel(),
            "Actor must be from the same channel as the"
            " actor it's being sent over");
        MOZ_RELEASE_ASSERT(
            aVar->CanSend(),
            "Actor must still be open when sending");
    }

    WriteIPDLParam(aMsg, aActor, id);
}

auto IPDLParamTraits<mozilla::PWebBrowserPersistResourcesChild*>::Read(
        const IPC::Message* aMsg,
        PickleIterator* aIter,
        mozilla::ipc::IProtocol* aActor,
        paramType* aVar) -> bool
{
    mozilla::Maybe<mozilla::ipc::IProtocol*> actor =
        aActor->ReadActor(aMsg, aIter, true, "PWebBrowserPersistResources", PWebBrowserPersistResourcesMsgStart);
    if (actor.isNothing()) {
        return false;
    }

    *aVar = static_cast<mozilla::PWebBrowserPersistResourcesChild*>(actor.value());
    return true;
}

} // namespace ipc
} // namespace mozilla
