ifndef INCLUDED_AUTOCONF_MK
INCLUDED_AUTOCONF_MK = autoconf-js.mk
include $(DEPTH)/config/emptyvars-js.mk
ACCESSIBILITY = 1
ACDEFINES = -DACCESSIBILITY=1 -DBUILD_CTYPES=1 -DCROSS_COMPILE='' -DENABLE_REMOTE_AGENT=1 -DENABLE_SHARED_MEMORY=1 -DENABLE_TESTS=1 -DENABLE_WASM_MULTI_VALUE=1 -DENABLE_WASM_REFTYPES=1 -DENABLE_WASM_SIMD=1 -DENABLE_WASM_SIMD_WORMHOLE=1 -DGL_PROVIDER_EGL=1 -DGTEST_HAS_RTTI=0 -DHAVE_64BIT_BUILD=1 -DHAVE_ALLOCA_H=1 -DHAVE_BYTESWAP_H=1 -DHAVE_CLOCK_MONOTONIC=1 -DHAVE_CPUID_H=1 -DHAVE_DIRENT_H=1 -DHAVE_DLOPEN=1 -DHAVE_FTS_H=1 -DHAVE_GETCONTEXT=1 -DHAVE_GETC_UNLOCKED=1 -DHAVE_GETOPT_H=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAVE_LANGINFO_CODESET=1 -DHAVE_LIBM=1 -DHAVE_LINUX_IF_ADDR_H=1 -DHAVE_LINUX_PERF_EVENT_H=1 -DHAVE_LINUX_QUOTA_H=1 -DHAVE_LINUX_RTNETLINK_H=1 -DHAVE_LOCALECONV=1 -DHAVE_LOCALTIME_R=1 -DHAVE_MALLOC_H=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MEMALIGN=1 -DHAVE_MEMFD_CREATE=1 -DHAVE_NETINET_IN_H=1 -DHAVE_NL_TYPES_H=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_POSIX_FALLOCATE=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_RES_NINIT=1 -DHAVE_SSIZE_T=1 -DHAVE_STDINT_H=1 -DHAVE_STRNDUP=1 -DHAVE_SYS_MOUNT_H=1 -DHAVE_SYS_QUEUE_H=1 -DHAVE_SYS_QUOTA_H=1 -DHAVE_SYS_STATFS_H=1 -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_THREAD_TLS_KEYWORD=1 -DHAVE_TM_ZONE_TM_GMTOFF=1 -DHAVE_UNISTD_H=1 -DHAVE_VALLOC=1 -DHAVE_VA_COPY=1 -DHAVE_VA_LIST_AS_ARRAY=1 -DHAVE_VISIBILITY_ATTRIBUTE=1 -DHAVE_VISIBILITY_HIDDEN_ATTRIBUTE=1 -DHAVE___CXA_DEMANGLE=1 -DJS_64BIT=1 -DJS_CODEGEN_X64=1 -DJS_DEFAULT_JITREPORT_GRANULARITY=3 -DJS_HAS_CTYPES=1 -DJS_HAS_INTL_API=1 -DJS_PUNBOX64=1 -DMALLOC_H='<malloc.h>' -DMALLOC_USABLE_SIZE_CONST_PTR='' -DMOZILLA_UAVERSION='"87.0"' -DMOZILLA_VERSION='"87.0"' -DMOZILLA_VERSION_U=87.0 -DMOZJS_MAJOR_VERSION=87 -DMOZJS_MINOR_VERSION=0 -DMOZ_AARCH64_JSCVT=0 -DMOZ_AV1=1 -DMOZ_BLOCK_PROFILE_DOWNGRADE=1 -DMOZ_BUILD_APP=browser -DMOZ_BUNDLED_FONTS=1 -DMOZ_DAV1D_ASM=1 -DMOZ_DEDICATED_PROFILES=1 -DMOZ_DLL_PREFIX='"lib"' -DMOZ_DLL_SUFFIX='".so"' -DMOZ_ENABLE_FORKSERVER=1 -DMOZ_ENABLE_SKIA=1 -DMOZ_FFMPEG=1 -DMOZ_FFVPX=1 -DMOZ_FMP4=1 -DMOZ_GECKO_PROFILER=1 -DMOZ_GECKO_PROFILER_PARSE_ELF=1 -DMOZ_GLEAN=1 -DMOZ_GLUE_IN_PROGRAM=1 -DMOZ_HAS_REMOTE=1 -DMOZ_INSTRUMENT_EVENT_LOOP=1 -DMOZ_LIBAV_FFT=1 -DMOZ_MEMORY=1 -DMOZ_NORMANDY=1 -DMOZ_OXIDIZED_BREAKPAD=1 -DMOZ_PEERCONNECTION=1 -DMOZ_PLACES=1 -DMOZ_PROFILER_MEMORY=1 -DMOZ_PULSEAUDIO=1 -DMOZ_RAW=1 -DMOZ_RUST_SIMD=1 -DMOZ_SAMPLE_TYPE_FLOAT32=1 -DMOZ_SCTP=1 -DMOZ_SERVICES_HEALTHREPORT=1 -DMOZ_SRTP=1 -DMOZ_STATIC_JS=1 -DMOZ_UPDATE_CHANNEL=release -DMOZ_VERIFY_MAR_SIGNATURE=1 -DMOZ_VORBIS=1 -DMOZ_WAYLAND=1 -DMOZ_WEBRTC=1 -DMOZ_WEBRTC_ASSERT_ALWAYS=1 -DMOZ_WEBRTC_SIGNALING=1 -DMOZ_WEBSPEECH=1 -DMOZ_WEBSPEECH_TEST_BACKEND=1 -DMOZ_WIDGET_GTK=1 -DMOZ_X11=1 -DNO_NSPR_10_SUPPORT=1 -DNS_PRINTING=1 -DNS_PRINT_PREVIEW=1 -DRELEASE_OR_BETA=1 -DSTATIC_JS_API=1 -DSTDC_HEADERS=1 -DUSE_SKIA=1 -DU_STATIC_IMPLEMENTATION=1 -DU_USING_ICU_NAMESPACE=0 -DVA_COPY=va_copy -DXP_LINUX=1 -DXP_UNIX=1 -D_REENTRANT=1
ANDROID_PACKAGE_NAME = org.mozilla.konke
AR = /home/worker/.mozbuild/clang/bin/llvm-ar
AR_FLAGS = crs $@
AS = /home/worker/.mozbuild/sccache/sccache /home/worker/.mozbuild/clang/bin/clang -std=gnu99
ASFLAGS = -fPIC -Wa,--noexecstack
ASOUTOPTION = -o 
AS_DASH_C_FLAG = -c
AWK = /usr/sbin/gawk
BINDGEN_SYSTEM_FLAGS = -x c++ -fno-sized-deallocation -fno-aligned-new -DTRACING=1 -DIMPL_LIBXUL -DMOZILLA_INTERNAL_API -DRUST_BINDGEN -DOS_POSIX=1 -DOS_LINUX=1 -std=gnu++17 -I/worker/build/obj-x86_64-pc-linux-gnu/dist/include/nspr
BUILD_BACKENDS = RecursiveMake FasterMake
BUILD_CTYPES = 1
CARGO = /home/worker/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo
CARGO_INCREMENTAL = 0
CBINDGEN = /home/worker/.mozbuild/cbindgen/cbindgen
CC = /home/worker/.mozbuild/sccache/sccache /home/worker/.mozbuild/clang/bin/clang -std=gnu99
CCACHE = /home/worker/.mozbuild/sccache/sccache
CC_BASE_FLAGS = -std=gnu99
CC_TYPE = clang
CC_VERSION = 11.0.1
CLANG_CXX = 1
COLOR_CFLAGS = -fcolor-diagnostics
COMPILE_ENVIRONMENT = 1
CPP = /home/worker/.mozbuild/sccache/sccache /home/worker/.mozbuild/clang/bin/clang -E -std=gnu99
CPU_ARCH = x86_64
CROSS_LIB = /usr/x86_64-pc-linux-gnu
CXX = /home/worker/.mozbuild/sccache/sccache /home/worker/.mozbuild/clang/bin/clang++ -std=gnu++17
CXXCPP = /home/worker/.mozbuild/sccache/sccache /home/worker/.mozbuild/clang/bin/clang++ -E -std=gnu++17
CXX_BASE_FLAGS = -std=gnu++17
DIST = /worker/build/obj-x86_64-pc-linux-gnu/dist
DLL_PREFIX = lib
DLL_SUFFIX = .so
DSO_LDOPTS = -shared -Wl,-z,defs -Wl,--gc-sections
DSO_PIC_CFLAGS = -fPIC
DUMP_SYMS = /home/worker/.mozbuild/dump_syms/dump_syms
ENABLE_GECKODRIVER = 1
ENABLE_MARIONETTE = 1
ENABLE_REMOTE_AGENT = 1
ENABLE_SHARED_MEMORY = 1
ENABLE_TESTS = 1
ENABLE_WASM_MULTI_VALUE = 1
ENABLE_WASM_REFTYPES = 1
ENABLE_WASM_SIMD = 1
ENABLE_WASM_SIMD_WORMHOLE = 1
EXPAND_LIBS_LIST_STYLE = linkerscript
FFI_TARGET = X86_64
FFI_TARGET_DIR = x86
FFVPX_ASFLAGS = -D__x86_64__ -DPIC -DELF -Pconfig_unix64.asm -Pdefaults_disabled.asm
FFVPX_USE_YASM = 1
FT2_LIBS = -lfreetype -lfontconfig -lfreetype
GCC_USE_GNU_LD = 1
GIT = /usr/sbin/git
GMAKE = /usr/sbin/make
GNU_AS = 1
GNU_CC = 1
GNU_CXX = 1
GRE_MILESTONE = 87.0
HAVE_64BIT_BUILD = 1
HAVE_CLOCK_MONOTONIC = 1
HAVE_GETCONTEXT = 1
HAVE_INTTYPES_H = 1
HAVE_LANGINFO_CODESET = 1
HAVE_LINUX_PERF_EVENT_H = 1
HOST_CC = /home/worker/.mozbuild/sccache/sccache /home/worker/.mozbuild/clang/bin/clang -std=gnu99
HOST_CC_BASE_FLAGS = -std=gnu99
HOST_CC_TYPE = clang
HOST_CC_VERSION = 11.0.1
HOST_CFLAGS = -DXP_UNIX
HOST_CPU_ARCH = x86_64
HOST_CXX = /home/worker/.mozbuild/sccache/sccache /home/worker/.mozbuild/clang/bin/clang++ -std=gnu++17
HOST_CXX_BASE_FLAGS = -std=gnu++17
HOST_DLL_PREFIX = lib
HOST_DLL_SUFFIX = .so
HOST_OPTIMIZE_FLAGS = -O3
HOST_OS_ARCH = Linux
INTEL_ARCHITECTURE = 1
IPDL_ROOT = /worker/build/obj-x86_64-pc-linux-gnu/ipc/ipdl
JS_CODEGEN_X64 = 1
JS_CONFIG_LIBS = -L/worker/build/obj-x86_64-pc-linux-gnu/dist/bin -lnspr4 -lplc4 -lplds4 -lm -ldl 
JS_CONFIG_MOZ_JS_LIBS = -L${libdir} -l${JS_LIBRARY_NAME}
JS_CONFIG_NAME = js-config
JS_DISABLE_SHELL = 1
JS_HAS_CTYPES = 1
JS_HAS_INTL_API = 1
JS_LIBRARY_NAME = mozjs
JS_SHELL_NAME = js
L10NBASEDIR = /home/worker/.mozbuild/l10n-central
LIBAV_FFT_ASFLAGS = -D__x86_64__ -DPIC -DELF
LIBFUZZER_FLAGS = -fsanitize-coverage=trace-pc-guard,trace-cmp
LIBJPEG_TURBO_ASFLAGS = -D__x86_64__ -DPIC -DELF
LIBJPEG_TURBO_USE_YASM = 1
LIB_PREFIX = lib
LIB_SUFFIX = a
LINKER_KIND = bfd
LLVM_OBJDUMP = /home/worker/.mozbuild/clang/bin/llvm-objdump
LLVM_PROFDATA = /home/worker/.mozbuild/clang/bin/llvm-profdata
M4 = /usr/sbin/m4
MAKENSISU_FLAGS = -nocd
MKCSHLIB = $(CC) $(COMPUTED_C_LDFLAGS) $(PGO_CFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -Wl,-h,$(DSO_SONAME) -o $@
MKSHLIB = $(CXX) $(COMPUTED_CXX_LDFLAGS) $(PGO_CFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -Wl,-h,$(DSO_SONAME) -o $@
MOZCONFIG = /worker/build/mozconfig
MOZILLA_SYMBOLVERSION = 87
MOZILLA_VERSION = 87.0
MOZJS_MAJOR_VERSION = 87
MOZJS_MINOR_VERSION = 0
MOZ_ADJUST_SDK_KEY = no-adjust-sdk-key
MOZ_APP_BASENAME = Konke
MOZ_APP_DISPLAYNAME = Konke Browser
MOZ_APP_NAME = konke
MOZ_APP_REMOTINGNAME = konke
MOZ_APP_VERSION = 87.0
MOZ_APP_VERSION_DISPLAY = 87.0
MOZ_AV1 = 1
MOZ_BING_API_CLIENTID = no-bing-api-clientid
MOZ_BING_API_KEY = no-bing-api-key
MOZ_BLOCK_PROFILE_DOWNGRADE = 1
MOZ_BUILD_APP = browser
MOZ_BUILD_NSPR = 1
MOZ_CLANG_PATH = /home/worker/.mozbuild/clang/bin/clang++
MOZ_CONFIGURE_OPTIONS = --enable-application=browser --enable-update-channel=release MOZ_APP_BASENAME=Konke --with-ccache=sccache --enable-hardening --with-app-name=konke --enable-rust-simd MAKE=/usr/sbin/make --enable-updater --with-branding=browser/branding/dot
MOZ_DAV1D_ASM = 1
MOZ_DEBUG_DEFINES = NDEBUG TRIMMED
MOZ_DEBUG_FLAGS = -g
MOZ_DEBUG_SYMBOLS = 1
MOZ_DEDICATED_PROFILES = 1
MOZ_EME_MODULES = widevine
MOZ_ENABLE_FORKSERVER = 1
MOZ_ENABLE_SKIA = 1
MOZ_FFMPEG = 1
MOZ_FFVPX = 1
MOZ_FIX_LINK_PATHS = -Wl,-rpath-link,/worker/build/obj-x86_64-pc-linux-gnu/dist/bin -Wl,-rpath-link,/usr/local/lib
MOZ_FMP4 = 1
MOZ_FRAMEPTR_FLAGS = -fomit-frame-pointer -funwind-tables
MOZ_GECKO_PROFILER = 1
MOZ_GECKO_PROFILER_PARSE_ELF = 1
MOZ_GLEAN = 1
MOZ_GLUE_IN_PROGRAM = 1
MOZ_GL_DEFAULT_PROVIDER = EGL
MOZ_GOOGLE_LOCATION_SERVICE_API_KEY = no-google-location-service-api-key
MOZ_GOOGLE_SAFEBROWSING_API_KEY = no-google-safebrowsing-api-key
MOZ_HARDENING_CFLAGS = -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection
MOZ_HARDENING_CFLAGS_JS = -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection
MOZ_HARDENING_LDFLAGS = -fstack-protector-strong -fstack-clash-protection
MOZ_HARDENING_LDFLAGS_JS = -fstack-protector-strong -fstack-clash-protection
MOZ_HAS_REMOTE = 1
MOZ_ICU_VERSION = 67
MOZ_INSTRUMENT_EVENT_LOOP = 1
MOZ_JAR_MAKER_FILE_FORMAT = symlink
MOZ_LEANPLUM_SDK_CLIENTID = no-leanplum-sdk-clientid
MOZ_LEANPLUM_SDK_KEY = no-leanplum-sdk-key
MOZ_LIBAV_FFT = 1
MOZ_LIBCLANG_PATH = /home/worker/.mozbuild/clang/lib
MOZ_MEMORY = 1
MOZ_MOZILLA_API_KEY = no-mozilla-api-key
MOZ_NEW_PASS_MANAGER_FLAGS = -fexperimental-new-pass-manager
MOZ_NORMANDY = 1
MOZ_NO_DEBUG_RTL = 1
MOZ_OPTIMIZE = 1
MOZ_OPTIMIZE_FLAGS = -O3
MOZ_OXIDIZED_BREAKPAD = 1
MOZ_PACKAGER_FORMAT = omni
MOZ_PANGO_CFLAGS = -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -pthread
MOZ_PANGO_LIBS = -lpangoft2-1.0 -lfontconfig -lfreetype -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo
MOZ_PDF_PRINTING = 1
MOZ_PEERCONNECTION = 1
MOZ_PGO_OPTIMIZE_FLAGS = -O3
MOZ_PLACES = 1
MOZ_POCKET_API_KEY = no-pocket-api-key
MOZ_PREF_EXTENSIONS = 1
MOZ_PROFILER_MEMORY = 1
MOZ_PROGRAM_LDFLAGS =  -pie
MOZ_PULSEAUDIO = 1
MOZ_PULSEAUDIO_CFLAGS = -D_REENTRANT
MOZ_PULSEAUDIO_LIBS = -lpulse -pthread
MOZ_RAW = 1
MOZ_RUST_DEFAULT_FLAGS = -C opt-level=2 -C debuginfo=2 --cap-lints warn
MOZ_RUST_SIMD = 1
MOZ_SAMPLE_TYPE_FLOAT32 = 1
MOZ_SCTP = 1
MOZ_SERVICES_HEALTHREPORT = 1
MOZ_SERVICES_SYNC = 1
MOZ_SRTP = 1
MOZ_SYNTH_SPEECHD = 1
MOZ_UI_LOCALE = en-US
MOZ_UPDATE_CHANNEL = release
MOZ_USING_COMPILER_WRAPPER = 1
MOZ_USING_SCCACHE = 1
MOZ_VERIFY_MAR_SIGNATURE = 1
MOZ_VORBIS = 1
MOZ_WAYLAND = 1
MOZ_WAYLAND_CFLAGS = -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread -I/usr/include/libdrm
MOZ_WAYLAND_LIBS = -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lxkbcommon -ldrm
MOZ_WEBRTC = 1
MOZ_WEBRTC_ASSERT_ALWAYS = 1
MOZ_WEBRTC_SIGNALING = 1
MOZ_WEBSPEECH = 1
MOZ_WEBSPEECH_TEST_BACKEND = 1
MOZ_WIDGET_TOOLKIT = gtk
MOZ_X11 = 1
NASM = /usr/sbin/nasm
NASM_ASFLAGS = -f elf64
NM = /home/worker/.mozbuild/clang/bin/llvm-nm
NODEJS = /home/worker/.mozbuild/node/bin/node
NSPR_CFLAGS = -I/worker/build/obj-x86_64-pc-linux-gnu/dist/include/nspr
NSPR_INCLUDE_DIR = /worker/build/obj-x86_64-pc-linux-gnu/dist/include/nspr
NSPR_LIBS = -L/worker/build/obj-x86_64-pc-linux-gnu/dist/bin -lnspr4 -lplc4 -lplds4
NSPR_LIB_DIR = /worker/build/obj-x86_64-pc-linux-gnu/dist/bin
NSS_CFLAGS = -I/worker/build/obj-x86_64-pc-linux-gnu/dist/include/nss
NS_PRINTING = 1
OBJ_SUFFIX = o
OMNIJAR_NAME = omni.ja
OS_ARCH = Linux
OS_CFLAGS = -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe
OS_COMPILE_CFLAGS = -include /worker/build/obj-x86_64-pc-linux-gnu/js/src/js-confdefs.h -DMOZILLA_CLIENT
OS_COMPILE_CXXFLAGS = -DMOZILLA_CLIENT -include /worker/build/obj-x86_64-pc-linux-gnu/js/src/js-confdefs.h
OS_CPPFLAGS = -Qunused-arguments
OS_CXXFLAGS = -Qunused-arguments -Wall -Wbitfield-enum-conversion -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wunreachable-code -Wunreachable-code-return -Wwrite-strings -Wno-invalid-offsetof -Wclass-varargs -Wempty-init-stmt -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wc++2a-compat -Wcomma -Wimplicit-fallthrough -Wunused-function -Wunused-variable -Wstring-conversion -Wtautological-overlap-compare -Wtautological-unsigned-enum-zero-compare -Wtautological-unsigned-zero-compare -Wno-error=tautological-type-limit-compare -Wno-inline-new-delete -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=backend-plugin -Wno-error=return-std-move -Wno-error=atomic-alignment -Wno-error=deprecated-copy -Wformat -Wformat-security -Wno-gnu-zero-variadic-macro-arguments -Wno-psabi -Wno-unknown-warning-option -fno-sized-deallocation -fno-aligned-new -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe
OS_LDFLAGS = -lpthread -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,-z,nocopyreloc -Wl,-Bsymbolic-functions -Wl,--build-id=sha1
OS_LIBS = -lm -ldl 
OS_TARGET = Linux
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PDF_SURFACE_FEATURE = #define CAIRO_HAS_PDF_SURFACE 1
PERL = /usr/sbin/perl
PGO_PROFILE_PATH = /worker/build/obj-x86_64-pc-linux-gnu/instrumented/merged.profdata
PKG_CONFIG = /usr/sbin/pkg-config
PKG_STRIP = 1
PREPROCESS_OPTION = -E -o 
PROFILE_GEN_CFLAGS = -fprofile-generate
PROFILE_GEN_LDFLAGS = -fprofile-generate
PROFILE_USE_CFLAGS = -fprofile-use=/worker/build/obj-x86_64-pc-linux-gnu/instrumented/merged.profdata -Wno-error=backend-plugin
PYTHON3 = /worker/build/obj-x86_64-pc-linux-gnu/_virtualenvs/init_py3/bin/python
PYTHON3_VERSION = 3.9.5
RELEASE_OR_BETA = 1
RUSTC = /home/worker/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc
RUSTC_COMMIT = 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
RUSTC_VERSION = 1.52.1
RUSTDOC = /usr/sbin/rustdoc
RUSTFMT = /usr/sbin/rustfmt
RUST_HOST_TARGET = x86_64-unknown-linux-gnu
RUST_TARGET = x86_64-unknown-linux-gnu
SHELL = /bin/sh
SKIA_INCLUDES = /gfx/skia /gfx/skia/skia
STRIP = strip
TAR = /usr/sbin/tar
TARGET_CPU = x86_64
TARGET_ENDIANNESS = little
TARGET_OS = linux-gnu
TARGET_XPCOM_ABI = x86_64-gcc3
UNZIP = /usr/sbin/unzip
USE_ELF_HACK = 1
VCS_CHECKOUT_TYPE = git
VISIBILITY_FLAGS = -I/worker/build/obj-x86_64-pc-linux-gnu/dist/system_wrappers -include /worker/build/config/gcc_hidden.h
VPX_USE_YASM = 1
WARNINGS_CFLAGS = -Qunused-arguments -Wall -Wbitfield-enum-conversion -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wunreachable-code -Wunreachable-code-return -Wclass-varargs -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wstring-conversion -Wtautological-overlap-compare -Wtautological-unsigned-enum-zero-compare -Wtautological-unsigned-zero-compare -Wno-error=tautological-type-limit-compare -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=backend-plugin -Wno-error=return-std-move -Wno-error=atomic-alignment -Wno-error=deprecated-copy -Wformat -Wformat-security -Wno-gnu-zero-variadic-macro-arguments -Werror=implicit-function-declaration -Wno-psabi
WASM_OBJ_SUFFIX = wasm
WEBIDL_ROOT = /worker/build/obj-x86_64-pc-linux-gnu/dom/bindings
WGET = /usr/sbin/wget
WRAP_SYSTEM_INCLUDES = 1
XARGS = /usr/sbin/xargs
XPCOM_ROOT = /worker/build/obj-x86_64-pc-linux-gnu/xpcom/components
X_PRE_LIBS =  -lSM -lICE
YASM = /usr/sbin/yasm
YASM_ASFLAGS = -f elf64 -rnasm -pnasm
YASM_HAS_AVX2 = 1
ZIP = /usr/sbin/zip
_AS = /home/worker/.mozbuild/clang/bin/clang
_CARGO = /usr/sbin/cargo
_CC = /home/worker/.mozbuild/clang/bin/clang
_CXX = /home/worker/.mozbuild/clang/bin/clang++
_DEPEND_CFLAGS = -MD -MP -MF $(MDDEPDIR)/$(@F).pp
_FONTCONFIG_CFLAGS = -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
_FONTCONFIG_LIBS = -lfontconfig -lfreetype
_FT2_CFLAGS = -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
_FT2_LIBS = -lfreetype
_HOST_CC = /home/worker/.mozbuild/clang/bin/clang
_HOST_CXX = /home/worker/.mozbuild/clang/bin/clang++
_HOST_DEPEND_CFLAGS = -MD -MP -MF $(MDDEPDIR)/$(@F).pp
_RUSTC = /usr/sbin/rustc
ac_configure_args =  --enable-updater --with-branding=browser/branding/dot --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu
autoconfmk = autoconf-js.mk
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = x86_64-pc-linux-gnu
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = x86_64-pc-linux-gnu
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target = x86_64-pc-linux-gnu
target_alias = x86_64-pc-linux-gnu
target_cpu = x86_64
target_os = linux-gnu
target_vendor = pc
top_srcdir = /worker/build/js/src/../..
include $(topsrcdir)/config/baseconfig.mk
endif
