//
// Automatically generated by ipdlc.
// Edit at your own risk
//

#ifndef PClassifierDummyChannel_h
#define PClassifierDummyChannel_h

#include "mozilla/Attributes.h"
#include "IPCMessageStart.h"
#include "mozilla/RefPtr.h"
#include "nsString.h"
#include "nsTArray.h"
#include "nsTHashtable.h"
#include "mozilla/MozPromise.h"
#include "mozilla/OperatorNewExtensions.h"
#include "mozilla/UniquePtr.h"
#include "mozilla/ipc/ByteBuf.h"
#include "mozilla/ipc/FileDescriptor.h"
#include "mozilla/ipc/ProtocolUtilsFwd.h"
#include "mozilla/ipc/Shmem.h"

namespace mozilla {
namespace net {
class PClassifierDummyChannelParent;
} // namespace net
} // namespace mozilla
namespace mozilla {
namespace net {
class PClassifierDummyChannelChild;
} // namespace net
} // namespace mozilla

//-----------------------------------------------------------------------------
// Code common to PClassifierDummyChannelChild and PClassifierDummyChannelParent
//
namespace mozilla {
namespace net {
namespace PClassifierDummyChannel {

nsresult
CreateEndpoints(
        base::ProcessId aParentDestPid,
        base::ProcessId aChildDestPid,
        mozilla::ipc::Endpoint<mozilla::net::PClassifierDummyChannelParent>* aParent,
        mozilla::ipc::Endpoint<mozilla::net::PClassifierDummyChannelChild>* aChild);

enum MessageType {
    PClassifierDummyChannelStart = PClassifierDummyChannelMsgStart << 16,
    Msg___delete____ID,
    Reply___delete____ID,
    PClassifierDummyChannelEnd
};

IPC::Message*
Msg___delete__(int32_t routingId);
IPC::Message*
Reply___delete__(int32_t routingId);



} // namespace PClassifierDummyChannel
} // namespace net
} // namespace mozilla

#endif // ifndef PClassifierDummyChannel_h
