//
// Automatically generated by ipdlc.
// Edit at your own risk
//

#ifndef PTRRService_h
#define PTRRService_h

#include "mozilla/Attributes.h"
#include "IPCMessageStart.h"
#include "mozilla/RefPtr.h"
#include "nsString.h"
#include "nsTArray.h"
#include "nsTHashtable.h"
#include "mozilla/MozPromise.h"
#include "mozilla/OperatorNewExtensions.h"
#include "mozilla/UniquePtr.h"
#include "mozilla/ipc/ByteBuf.h"
#include "mozilla/ipc/FileDescriptor.h"
#include "mozilla/ipc/ProtocolUtilsFwd.h"
#include "mozilla/ipc/Shmem.h"
#include "mozilla/psm/PSMIPCTypes.h"

namespace mozilla {
namespace net {
class PTRRServiceParent;
} // namespace net
} // namespace mozilla
namespace mozilla {
namespace net {
class PTRRServiceChild;
} // namespace net
} // namespace mozilla

//-----------------------------------------------------------------------------
// Code common to PTRRServiceChild and PTRRServiceParent
//
namespace mozilla {
namespace net {
namespace PTRRService {

nsresult
CreateEndpoints(
        base::ProcessId aParentDestPid,
        base::ProcessId aChildDestPid,
        mozilla::ipc::Endpoint<mozilla::net::PTRRServiceParent>* aParent,
        mozilla::ipc::Endpoint<mozilla::net::PTRRServiceChild>* aChild);

enum MessageType {
    PTRRServiceStart = PTRRServiceMsgStart << 16,
    Msg___delete____ID,
    Reply___delete____ID,
    Msg_UpdatePlatformDNSInformation__ID,
    Msg_UpdateParentalControlEnabled__ID,
    Msg_ClearDNSCache__ID,
    Msg_SetDetectedTrrURI__ID,
    PTRRServiceEnd
};

IPC::Message*
Msg___delete__(int32_t routingId);
IPC::Message*
Reply___delete__(int32_t routingId);

IPC::Message*
Msg_UpdatePlatformDNSInformation(int32_t routingId);

IPC::Message*
Msg_UpdateParentalControlEnabled(int32_t routingId);

IPC::Message*
Msg_ClearDNSCache(int32_t routingId);

IPC::Message*
Msg_SetDetectedTrrURI(int32_t routingId);



} // namespace PTRRService
} // namespace net
} // namespace mozilla

#endif // ifndef PTRRService_h
