//
// Automatically generated by ipdlc.
// Edit at your own risk
//

#ifndef PWebSocketEventListener_h
#define PWebSocketEventListener_h

#include "mozilla/Attributes.h"
#include "IPCMessageStart.h"
#include "mozilla/RefPtr.h"
#include "nsString.h"
#include "nsTArray.h"
#include "nsTHashtable.h"
#include "mozilla/MozPromise.h"
#include "mozilla/OperatorNewExtensions.h"
#include "mozilla/UniquePtr.h"
#include "mozilla/ipc/ByteBuf.h"
#include "mozilla/ipc/FileDescriptor.h"
#include "mozilla/ipc/ProtocolUtilsFwd.h"
#include "mozilla/ipc/Shmem.h"

namespace mozilla {
namespace net {
class PWebSocketEventListenerParent;
} // namespace net
} // namespace mozilla
namespace mozilla {
namespace net {
class PWebSocketEventListenerChild;
} // namespace net
} // namespace mozilla

//-----------------------------------------------------------------------------
// Code common to PWebSocketEventListenerChild and PWebSocketEventListenerParent
//
namespace mozilla {
namespace net {
namespace PWebSocketEventListener {

nsresult
CreateEndpoints(
        base::ProcessId aParentDestPid,
        base::ProcessId aChildDestPid,
        mozilla::ipc::Endpoint<mozilla::net::PWebSocketEventListenerParent>* aParent,
        mozilla::ipc::Endpoint<mozilla::net::PWebSocketEventListenerChild>* aChild);

enum MessageType {
    PWebSocketEventListenerStart = PWebSocketEventListenerMsgStart << 16,
    Msg_WebSocketCreated__ID,
    Msg_WebSocketOpened__ID,
    Msg_WebSocketMessageAvailable__ID,
    Msg_WebSocketClosed__ID,
    Msg_FrameReceived__ID,
    Msg_FrameSent__ID,
    Msg___delete____ID,
    Reply___delete____ID,
    Msg_Close__ID,
    PWebSocketEventListenerEnd
};

IPC::Message*
Msg_WebSocketCreated(int32_t routingId);

IPC::Message*
Msg_WebSocketOpened(int32_t routingId);

IPC::Message*
Msg_WebSocketMessageAvailable(int32_t routingId);

IPC::Message*
Msg_WebSocketClosed(int32_t routingId);

IPC::Message*
Msg_FrameReceived(int32_t routingId);

IPC::Message*
Msg_FrameSent(int32_t routingId);

IPC::Message*
Msg___delete__(int32_t routingId);
IPC::Message*
Reply___delete__(int32_t routingId);

IPC::Message*
Msg_Close(int32_t routingId);



} // namespace PWebSocketEventListener
} // namespace net
} // namespace mozilla

#endif // ifndef PWebSocketEventListener_h
