# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DMOZ_APP_VERSION=87.0 -DMOZ_APP_VERSION_DISPLAY=87.0 -DAPP_LICENSE_BLOCK=/worker/build/browser/base/content/overrides/app-license.html -DCONTEXT_COPY_IMAGE_CONTENTS=1 -DMENUBAR_CAN_AUTOHIDE=1
DIST_SUBDIR = browser
FINAL_TARGET = $(if $(XPI_NAME),$(DIST)/xpi-stage/$(XPI_NAME),$(DIST)/bin)$(DIST_SUBDIR:%=/%)
JAR_MANIFEST := /worker/build/browser/base/jar.mn
